steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/helm:$TAG_NAME',
      '-t', 'gcr.io/$PROJECT_ID/helm:latest',
      '--build-arg', 'HELM_VERSION=v2.14.0', 
      '.'
  ]

images: [
  'gcr.io/$PROJECT_ID/helm'
]
